export interface ProductPriceTier {
  "50": number;
  "100": number;
  "300": number;
  "500": number;
  [key: string]: number;
}

export interface ProductSpecifications {
  [key: string]: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  categoryId: string;
  size_inches: string;
  size_inches_short: string;
  size_cm: string;
  length_in: number;
  width_in: number;
  height_in: number;
  length_cm: number;
  width_cm: number;
  height_cm: number;
  description: string;
  features: string[];
  prices: ProductPriceTier;
  contact_number: string;
  availability: string;
  image: string;
  specifications: ProductSpecifications;
  rating?: number;
  reviewsCount?: number;
  isPopular?: boolean;
}

export const PRODUCTS: Product[] = [
  {
    id: "mb-1",
    slug: "mailer-box-3-3x2-75x1",
    name: "3.30 X 2.75 X 1 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "3.3 inch X 2.75 inch X 1 inch",
    size_inches_short: "3.3x2.75x1",
    size_cm: "8.38 cm x 6.99 cm x 2.54 cm",
    length_in: 3.3,
    width_in: 2.75,
    height_in: 1.0,
    length_cm: 8.38,
    width_cm: 6.99,
    height_cm: 2.54,
    description: "Compact Kraft Flap Mailer Box manufactured using high-grade E-flute corrugated cardboard.",
    features: ["Self-Locking Flaps", "E-Flute Board", "Eco-Friendly Kraft"],
    prices: { "50": 145, "100": 275, "300": 750, "500": 1450 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_4_4_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 128,
    isPopular: true
  },
  {
    id: "mb-2",
    slug: "mailer-box-4x4x1-5",
    name: "4 X 4 X 1.5 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "4 inch X 4 inch X 1.5 inch",
    size_inches_short: "4x4x1.5",
    size_cm: "10.16 cm x 10.16 cm x 3.81 cm",
    length_in: 4.0,
    width_in: 4.0,
    height_in: 1.5,
    length_cm: 10.16,
    width_cm: 10.16,
    height_cm: 3.81,
    description: "Slim flap mailer box for small accessories, electronics, and cosmetics.",
    features: ["Compact Depth", "Crush Resistant", "Easy Assembly"],
    prices: { "50": 215, "100": 405, "300": 1125, "500": 2150 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_4_4_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 94,
    isPopular: true
  },
  {
    id: "mb-3",
    slug: "mailer-box-4-6x3-7x1-6",
    name: "4.60 X 3.70 X 1.60 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "4.6 inch X 3.7 inch X 1.6 inch",
    size_inches_short: "4.6x3.7x1.6",
    size_cm: "11.68 cm x 9.40 cm x 4.06 cm",
    length_in: 4.6,
    width_in: 3.7,
    height_in: 1.6,
    length_cm: 11.68,
    width_cm: 9.40,
    height_cm: 4.06,
    description: "Versatile small Kraft mailer box for ecommerce shipping.",
    features: ["Self-Locking Wings", "Biodegradable Kraft"],
    prices: { "50": 245, "100": 465, "300": 1290, "500": 2450 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_4_4_2.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 212
  },
  {
    id: "mb-4",
    slug: "mailer-box-6x4x2",
    name: "6 X 4 X 2 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "6 inch X 4 inch X 2 inch",
    size_inches_short: "6x4x2",
    size_cm: "15.24 cm x 10.16 cm x 5.08 cm",
    length_in: 6.0,
    width_in: 4.0,
    height_in: 2.0,
    length_cm: 15.24,
    width_cm: 10.16,
    height_cm: 5.08,
    description: "Popular medium flap mailer box for D2C products and retail merchandise.",
    features: ["3-Ply Construction", "Dust-Proof Wings"],
    prices: { "50": 329.5, "100": 625, "300": 1725, "500": 3295 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_4_2.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 57,
    isPopular: true
  },
  {
    id: "mb-5",
    slug: "mailer-box-5x3x2",
    name: "5 X 3 X 2 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "5 inch X 3 inch X 2 inch",
    size_inches_short: "5x3x2",
    size_cm: "12.70 cm x 7.62 cm x 5.08 cm",
    length_in: 5.0,
    width_in: 3.0,
    height_in: 2.0,
    length_cm: 12.70,
    width_cm: 7.62,
    height_cm: 5.08,
    description: "Small depth Kraft box for compact gift items and cosmetics.",
    features: ["Strong Flute", "Recyclable"],
    prices: { "50": 255, "100": 485, "300": 1350, "500": 2550 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_5_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.8,
    reviewsCount: 88
  },
  {
    id: "mb-6",
    slug: "mailer-box-5-5x4x1-5",
    name: "5.5 X 4 X 1.5 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "5.5 inch X 4 inch X 1.5 inch",
    size_inches_short: "5.5x4x1.5",
    size_cm: "13.97 cm x 10.16 cm x 3.81 cm",
    length_in: 5.5,
    width_in: 4.0,
    height_in: 1.5,
    length_cm: 13.97,
    width_cm: 10.16,
    height_cm: 3.81,
    description: "Slim profile mailer box suitable for flat stationery and accessories.",
    features: ["Slim Depth", "Interlocking Flaps"],
    prices: { "50": 290, "100": 550, "300": 1530, "500": 2900 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_5_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.9,
    reviewsCount: 76
  },
  {
    id: "mb-7",
    slug: "mailer-box-6x6x3",
    name: "6 X 6 X 3 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "6 inch X 6 inch X 3 inch",
    size_inches_short: "6x6x3",
    size_cm: "15.24 cm x 15.24 cm x 7.62 cm",
    length_in: 6.0,
    width_in: 6.0,
    height_in: 3.0,
    length_cm: 15.24,
    width_cm: 15.24,
    height_cm: 7.62,
    description: "Square mailer box for mugs, candles, and bulky gift items.",
    features: ["Square Design", "High Load Capacity"],
    prices: { "50": 410, "100": 780, "300": 2160, "500": 4100 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_4_2.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.7,
    reviewsCount: 105
  },
  {
    id: "mb-8",
    slug: "mailer-box-7x5x2",
    name: "7 X 5 X 2 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "7 inch X 5 inch X 2 inch",
    size_inches_short: "7x5x2",
    size_cm: "17.78 cm x 12.70 cm x 5.08 cm",
    length_in: 7.0,
    width_in: 5.0,
    height_in: 2.0,
    length_cm: 17.78,
    width_cm: 12.70,
    height_cm: 5.08,
    description: "Medium Kraft box designed for apparel, accessories, and book shipments.",
    features: ["Sturdy Board", "Clean Edges"],
    prices: { "50": 375, "100": 710, "300": 1980, "500": 3750 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_5_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 62
  },
  {
    id: "mb-9",
    slug: "mailer-box-8x5x3",
    name: "8 X 5 X 3 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "8 inch X 5 inch X 3 inch",
    size_inches_short: "8x5x3",
    size_cm: "20.32 cm x 12.70 cm x 7.62 cm",
    length_in: 8.0,
    width_in: 5.0,
    height_in: 3.0,
    length_cm: 20.32,
    width_cm: 12.70,
    height_cm: 7.62,
    description: "Spacious mailer box ideal for multiple retail items and skincare jars.",
    features: ["Spacious Depth", "High Crush Strength"],
    prices: { "50": 455, "100": 865, "300": 2400, "500": 4550 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/mailer-boxes.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.9,
    reviewsCount: 143,
    isPopular: true
  },
  {
    id: "mb-10",
    slug: "mailer-box-8x8x4",
    name: "8 X 8 X 4 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "8 inch X 8 inch X 4 inch",
    size_inches_short: "8x8x4",
    size_cm: "20.32 cm x 20.32 cm x 10.16 cm",
    length_in: 8.0,
    width_in: 8.0,
    height_in: 4.0,
    length_cm: 20.32,
    width_cm: 20.32,
    height_cm: 10.16,
    description: "Deep square mailer box for bulky merchandise and subscription kits.",
    features: ["Extra Depth", "Heavy Duty Flute"],
    prices: { "50": 575, "100": 1090, "300": 3030, "500": 5750 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_4_2.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.6,
    reviewsCount: 59
  },
  {
    id: "mb-11",
    slug: "mailer-box-9x6x3",
    name: "9 X 6 X 3 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "9 inch X 6 inch X 3 inch",
    size_inches_short: "9x6x3",
    size_cm: "22.86 cm x 15.24 cm x 7.62 cm",
    length_in: 9.0,
    width_in: 6.0,
    height_in: 3.0,
    length_cm: 22.86,
    width_cm: 15.24,
    height_cm: 7.62,
    description: "Large rectangular mailer box for shoes, clothing, and electronics.",
    features: ["Large Footprint", "Sturdy Side Wings"],
    prices: { "50": 540, "100": 1025, "300": 2850, "500": 5400 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/mailer-boxes.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.8,
    reviewsCount: 137,
    isPopular: true
  },
  {
    id: "mb-12",
    slug: "mailer-box-9x9x4",
    name: "9 X 9 X 4 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "9 inch X 9 inch X 4 inch",
    size_inches_short: "9x9x4",
    size_cm: "22.86 cm x 22.86 cm x 10.16 cm",
    length_in: 9.0,
    width_in: 9.0,
    height_in: 4.0,
    length_cm: 22.86,
    width_cm: 22.86,
    height_cm: 10.16,
    description: "Heavy duty square mailer box for large items and multi-product bundles.",
    features: ["Heavy Duty", "Secure Lock"],
    prices: { "50": 660, "100": 1255, "300": 3480, "500": 6600 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_4_4_2.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 82
  },
  {
    id: "mb-13",
    slug: "mailer-box-10x6x4",
    name: "10 X 6 X 4 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "10 inch X 6 inch X 4 inch",
    size_inches_short: "10x6x4",
    size_cm: "25.40 cm x 15.24 cm x 10.16 cm",
    length_in: 10.0,
    width_in: 6.0,
    height_in: 4.0,
    length_cm: 25.40,
    width_cm: 15.24,
    height_cm: 10.16,
    description: "Elongated Kraft mailer box suitable for bottles, tumblers, and tools.",
    features: ["Elongated Di-line", "High Edge Crush Strength"],
    prices: { "50": 645, "100": 1225, "300": 3400, "500": 6450 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/mailer-boxes.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.7,
    reviewsCount: 119
  },
  {
    id: "mb-14",
    slug: "mailer-box-10x8x3",
    name: "10 X 8 X 3 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "10 inch X 8 inch X 3 inch",
    size_inches_short: "10x8x3",
    size_cm: "25.40 cm x 20.32 cm x 7.62 cm",
    length_in: 10.0,
    width_in: 8.0,
    height_in: 3.0,
    length_cm: 25.40,
    width_cm: 20.32,
    height_cm: 7.62,
    description: "Wide mailer box for folded shirts, jeans, and catalog shipments.",
    features: ["Wide Base", "Crease-Proof Edges"],
    prices: { "50": 675, "100": 1285, "300": 3570, "500": 6750 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_5_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.9,
    reviewsCount: 41
  },
  {
    id: "mb-15",
    slug: "mailer-box-10x10x4",
    name: "10 X 10 X 4 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "10 inch X 10 inch X 4 inch",
    size_inches_short: "10x10x4",
    size_cm: "25.40 cm x 25.40 cm x 10.16 cm",
    length_in: 10.0,
    width_in: 10.0,
    height_in: 4.0,
    length_cm: 25.40,
    width_cm: 25.40,
    height_cm: 10.16,
    description: "Large square mailer box for subscription hampers and gift sets.",
    features: ["Extra Large Volume", "Double Wall Reinforced Sides"],
    prices: { "50": 840, "100": 1595, "300": 4430, "500": 8400 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/mailer-boxes.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 164,
    isPopular: true
  },
  {
    id: "mb-16",
    slug: "mailer-box-11x8-5x5-5",
    name: "11 X 8.5 X 5.5 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "11 inch X 8.5 inch X 5.5 inch",
    size_inches_short: "11x8.5x5.5",
    size_cm: "27.94 cm x 21.59 cm x 13.97 cm",
    length_in: 11.0,
    width_in: 8.5,
    height_in: 5.5,
    length_cm: 27.94,
    width_cm: 21.59,
    height_cm: 13.97,
    description: "Deep heavy-duty mailer box for electronics, boots, and industrial parts.",
    features: ["Deep Interior", "Impact Absorbing"],
    prices: { "50": 925, "100": 1755, "300": 4880, "500": 9250 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/box_6_4_2.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.8,
    reviewsCount: 73
  },
  {
    id: "mb-17",
    slug: "mailer-box-12x10x4",
    name: "12 X 10 X 4 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "12 inch X 10 inch X 4 inch",
    size_inches_short: "12x10x4",
    size_cm: "30.48 cm x 25.40 cm x 10.16 cm",
    length_in: 12.0,
    width_in: 10.0,
    height_in: 4.0,
    length_cm: 30.48,
    width_cm: 25.40,
    height_cm: 10.16,
    description: "Maximum size flap mailer box engineered for bulk shipments and corporate gifts.",
    features: ["Maximum Capacity", "Locking Wing Flaps"],
    prices: { "50": 1050, "100": 1995, "300": 5550, "500": 10500 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/mailer-boxes.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 5.0,
    reviewsCount: 92,
    isPopular: true
  },
  {
    id: "mb-18",
    slug: "mailer-box-3x3x1",
    name: "3 X 3 X 1 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "3 inch X 3 inch X 1 inch",
    size_inches_short: "3x3x1",
    size_cm: "7.62 cm x 7.62 cm x 2.54 cm",
    length_in: 3.0,
    width_in: 3.0,
    height_in: 1.0,
    length_cm: 7.62,
    width_cm: 7.62,
    height_cm: 2.54,
    description: "Miniature mailer box for rings, earrings, and micro components.",
    features: ["Miniature Size", "Lightweight"],
    prices: { "50": 125, "100": 240, "300": 650, "500": 1250 },
    contact_number: "+91 89039 27262",
    availability: "Out of Stock",
    image: "/images/box_4_4_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.5,
    reviewsCount: 18
  },
  {
    id: "mb-19",
    slug: "mailer-box-6-5x4-5x2",
    name: "6.5 X 4.5 X 2 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "6.5 inch X 4.5 inch X 2 inch",
    size_inches_short: "6.5x4.5x2",
    size_cm: "16.51 cm x 11.43 cm x 5.08 cm",
    length_in: 6.5,
    width_in: 4.5,
    height_in: 2.0,
    length_cm: 16.51,
    width_cm: 11.43,
    height_cm: 5.08,
    description: "Medium depth mailer box for specialized gadgets and accessories.",
    features: ["Custom Flute", "Secure Seal"],
    prices: { "50": 360, "100": 680, "300": 1900, "500": 3600 },
    contact_number: "+91 89039 27262",
    availability: "Out of Stock",
    image: "/images/box_6_4_2.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.6,
    reviewsCount: 29
  },
  {
    id: "mb-20",
    slug: "mailer-box-8x6x2",
    name: "8 X 6 X 2 Inch Mailer Box",
    category: "Mailer Boxes",
    categorySlug: "mailer-boxes",
    categoryId: "mailer-boxes",
    size_inches: "8 inch X 6 inch X 2 inch",
    size_inches_short: "8x6x2",
    size_cm: "20.32 cm x 15.24 cm x 5.08 cm",
    length_in: 8.0,
    width_in: 6.0,
    height_in: 2.0,
    length_cm: 20.32,
    width_cm: 15.24,
    height_cm: 5.08,
    description: "Flat medium mailer box for books and flat merchandise.",
    features: ["Flat Profile", "Strong Edges"],
    prices: { "50": 445, "100": 845, "300": 2350, "500": 4450 },
    contact_number: "+91 89039 27262",
    availability: "Out of Stock",
    image: "/images/box_6_5_1_5.png",
    specifications: { "Box Type": "Mailer Box", "Material": "Corrugated Cardboard" },
    rating: 4.7,
    reviewsCount: 34
  },
  {
    id: "cb-1",
    slug: "corrugated-box-8x8x8-3ply",
    name: "8 X 8 X 8 Inch 3-Ply Box",
    category: "Corrugated Boxes",
    categorySlug: "corrugated-boxes",
    categoryId: "corrugated-boxes",
    size_inches: "8 inch X 8 inch X 8 inch",
    size_inches_short: "8x8x8",
    size_cm: "20.32 cm x 20.32 cm x 20.32 cm",
    length_in: 8.0,
    width_in: 8.0,
    height_in: 8.0,
    length_cm: 20.32,
    width_cm: 20.32,
    height_cm: 20.32,
    description: "Single wall 3-ply cube corrugated box for general storage, packing, and courier shipping.",
    features: ["Single Wall 3-Ply", "High Stacking Strength", "Eco-Friendly Kraft"],
    prices: { "50": 425, "100": 850, "300": 2400, "500": 4250 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-boxes.png",
    specifications: { "Box Type": "Corrugated Box", "Material": "3-Ply Single Wall" },
    rating: 4.7,
    reviewsCount: 45,
    isPopular: true
  },
  {
    id: "cb-2",
    slug: "corrugated-box-10x10x10-3ply",
    name: "10 X 10 X 10 Inch 3-Ply Box",
    category: "Corrugated Boxes",
    categorySlug: "corrugated-boxes",
    categoryId: "corrugated-boxes",
    size_inches: "10 inch X 10 inch X 10 inch",
    size_inches_short: "10x10x10",
    size_cm: "25.40 cm x 25.40 cm x 25.40 cm",
    length_in: 10.0,
    width_in: 10.0,
    height_in: 10.0,
    length_cm: 25.40,
    width_cm: 25.40,
    height_cm: 25.40,
    description: "Versatile 3-ply cube shipping box for medium-weight goods and retail storage.",
    features: ["Single Wall 3-Ply", "Impact Absorbing", "Standard RSC"],
    prices: { "50": 640, "100": 1280, "300": 3600, "500": 6400 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-boxes.png",
    specifications: { "Box Type": "Corrugated Box", "Material": "3-Ply Single Wall" },
    rating: 4.8,
    reviewsCount: 62,
    isPopular: true
  },
  {
    id: "cb-3",
    slug: "corrugated-box-12x9x9-3ply",
    name: "12 X 9 X 9 Inch 3-Ply Box",
    category: "Corrugated Boxes",
    categorySlug: "corrugated-boxes",
    categoryId: "corrugated-boxes",
    size_inches: "12 inch X 9 inch X 9 inch",
    size_inches_short: "12x9x9",
    size_cm: "30.48 cm x 22.86 cm x 22.86 cm",
    length_in: 12.0,
    width_in: 9.0,
    height_in: 9.0,
    length_cm: 30.48,
    width_cm: 22.86,
    height_cm: 22.86,
    description: "Popular rectangular 3-ply box for electronics, appliances, and office supplies.",
    features: ["Single Wall 3-Ply", "Crush Proof Flutes", "Recyclable"],
    prices: { "50": 725, "100": 1450, "300": 4050, "500": 7250 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-boxes.png",
    specifications: { "Box Type": "Corrugated Box", "Material": "3-Ply Single Wall" },
    rating: 5.0,
    reviewsCount: 88,
    isPopular: true
  },
  {
    id: "cb-4",
    slug: "corrugated-box-14x10x10-5ply",
    name: "14 X 10 X 10 Inch 5-Ply Box",
    category: "Corrugated Boxes",
    categorySlug: "corrugated-boxes",
    categoryId: "corrugated-boxes",
    size_inches: "14 inch X 10 inch X 10 inch",
    size_inches_short: "14x10x10",
    size_cm: "35.56 cm x 25.40 cm x 25.40 cm",
    length_in: 14.0,
    width_in: 10.0,
    height_in: 10.0,
    length_cm: 35.56,
    width_cm: 25.40,
    height_cm: 25.40,
    description: "Double wall 5-ply heavy duty corrugated carton for fragile or heavy items up to 25 kg.",
    features: ["Double Wall 5-Ply", "Maximum Compression Strength", "Export Grade"],
    prices: { "50": 1100, "100": 2200, "300": 6300, "500": 11000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-boxes.png",
    specifications: { "Box Type": "Corrugated Box", "Material": "5-Ply Double Wall" },
    rating: 4.9,
    reviewsCount: 76
  },
  {
    id: "cb-5",
    slug: "corrugated-box-16x12x12-5ply",
    name: "16 X 12 X 12 Inch 5-Ply Box",
    category: "Corrugated Boxes",
    categorySlug: "corrugated-boxes",
    categoryId: "corrugated-boxes",
    size_inches: "16 inch X 12 inch X 12 inch",
    size_inches_short: "16x12x12",
    size_cm: "40.64 cm x 30.48 cm x 30.48 cm",
    length_in: 16.0,
    width_in: 12.0,
    height_in: 12.0,
    length_cm: 40.64,
    width_cm: 30.48,
    height_cm: 30.48,
    description: "Large 5-ply heavy duty shipping box for industrial parts, relocation, and bulk storage.",
    features: ["Double Wall 5-Ply", "Heavy Duty Load", "Moisture Resistant"],
    prices: { "50": 1425, "100": 2850, "300": 8100, "500": 14250 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-boxes.png",
    specifications: { "Box Type": "Corrugated Box", "Material": "5-Ply Double Wall" },
    rating: 4.6,
    reviewsCount: 39
  },
  {
    id: "cb-6",
    slug: "corrugated-box-18x18x18-5ply",
    name: "18 X 18 X 18 Inch 5-Ply Box",
    category: "Corrugated Boxes",
    categorySlug: "corrugated-boxes",
    categoryId: "corrugated-boxes",
    size_inches: "18 inch X 18 inch X 18 inch",
    size_inches_short: "18x18x18",
    size_cm: "45.72 cm x 45.72 cm x 45.72 cm",
    length_in: 18.0,
    width_in: 18.0,
    height_in: 18.0,
    length_cm: 45.72,
    width_cm: 45.72,
    height_cm: 45.72,
    description: "Extra large 5-ply master carton for bulk cargo and heavy warehousing.",
    features: ["Extra Large Master Carton", "Double Wall 5-Ply", "Maximum Stacking Load"],
    prices: { "50": 2400, "100": 4800, "300": 13800, "500": 24000 },
    contact_number: "+91 89039 27262",
    availability: "Out of Stock",
    image: "/images/corrugated-boxes.png",
    specifications: { "Box Type": "Corrugated Box", "Material": "5-Ply Double Wall" },
    rating: 4.5,
    reviewsCount: 14
  },
  {
    id: "sb-8-6-4",
    slug: "heavy-duty-shipping-box-8x6x4",
    name: "Ecommerce Shipping Carton - 8x6x4 Inch",
    category: "Shipping Boxes",
    categorySlug: "shipping-boxes",
    categoryId: "shipping-boxes",
    size_inches: "8 inch X 6 inch X 4 inch",
    size_inches_short: "8x6x4",
    size_cm: "20.32 cm x 15.24 cm x 10.16 cm",
    length_in: 8.0,
    width_in: 6.0,
    height_in: 4.0,
    length_cm: 20.32,
    width_cm: 15.24,
    height_cm: 10.16,
    description: "Standard RSC brown shipping carton designed specifically for Amazon, Flipkart, and Shopify ecommerce merchant fulfillment.",
    features: [
      "Standard Postal Size Approved",
      "Crush Proof Corners",
      "Easy Tape Sealing Flaps",
      "100% Recyclable Board"
    ],
    prices: {
      "50": 550.0,
      "100": 1020.0,
      "300": 2850.0,
      "500": 4400.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/shipping-boxes.png",
    specifications: {
      "Box Type": "Shipping Box",
      "Material": "Heavy Duty Kraft",
      "Finish": "Standard Brown",
      "Usage": "Freight & Shipping",
      "Customization": "Available",
      "Country of Origin": "India"
    },
    rating: 4.8,
    reviewsCount: 142
  },
  {
    id: "pb-10-10-1-5",
    slug: "kraft-corrugated-pizza-box-10x10",
    name: "Kraft Pizza Box - 10x10x1.5 Inch",
    category: "Pizza Boxes",
    categorySlug: "pizza-boxes",
    categoryId: "pizza-boxes",
    size_inches: "10 inch X 10 inch X 1.5 inch",
    size_inches_short: "10x10x1.5",
    size_cm: "25.40 cm x 25.40 cm x 3.81 cm",
    length_in: 10.0,
    width_in: 10.0,
    height_in: 1.5,
    length_cm: 25.40,
    width_cm: 25.40,
    height_cm: 3.81,
    description: "Heat-retaining corrugated Kraft pizza box for pizzerias, bakeries, and cloud kitchens. Features steam vents to prevent soggy crusts.",
    features: [
      "Food Grade Virgin Paper",
      "Steam Release Air Vents",
      "High Thermal Insulation",
      "Rigid Non-Bending Lid"
    ],
    prices: {
      "50": 480.0,
      "100": 900.0,
      "300": 2500.0,
      "500": 3900.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/pizza-boxes.png",
    specifications: {
      "Box Type": "Pizza Box",
      "Material": "Food Safe Kraft Corrugated",
      "Finish": "Natural Brown",
      "Usage": "Food Delivery & Bakery",
      "Customization": "Logo Printing Available",
      "Country of Origin": "India"
    },
    rating: 4.9,
    reviewsCount: 112
  },
  {
    id: "mc-5-3-2",
    slug: "mono-folding-carton-5x3x2",
    name: "Mono Folding Carton - 5x3x2 Inch",
    category: "Mono Cartons",
    categorySlug: "mono-cartons",
    categoryId: "mono-cartons",
    size_inches: "5 inch X 3 inch X 2 inch",
    size_inches_short: "5x3x2",
    size_cm: "12.70 cm x 7.62 cm x 5.08 cm",
    length_in: 5.0,
    width_in: 3.0,
    height_in: 2.0,
    length_cm: 12.70,
    width_cm: 7.62,
    height_cm: 5.08,
    description: "Sleek SBS paperboard mono folding carton crafted for cosmetic, pharmaceutical, and retail product packaging.",
    features: [
      "350 GSM Premium SBS Board",
      "Vibrant Offset Print Compatible",
      "Tuck End Closure",
      "Lightweight Retail Ready"
    ],
    prices: {
      "50": 340.0,
      "100": 620.0,
      "300": 1700.0,
      "500": 2600.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/mono-cartons.png",
    specifications: {
      "Box Type": "Mono Carton",
      "Material": "SBS Paperboard",
      "Finish": "Gloss / Matte",
      "Usage": "Retail Packaging",
      "Customization": "Available",
      "Country of Origin": "India"
    },
    rating: 4.7,
    reviewsCount: 54
  },
  {
    id: "cb-bag-10-14",
    slug: "tamper-proof-courier-bag-10x14",
    name: "Tamper-Proof Courier Bag - 10x14 Inch (Pack of 100)",
    category: "Courier Bags",
    categorySlug: "courier-bags",
    categoryId: "courier-bags",
    size_inches: "10 inch X 14 inch",
    size_inches_short: "10x14",
    size_cm: "25.40 cm x 35.56 cm",
    length_in: 10.0,
    width_in: 14.0,
    height_in: 0.1,
    length_cm: 25.40,
    width_cm: 35.56,
    height_cm: 0.1,
    description: "High-security poly courier mailer bags with hot-melt adhesive seal flap and POD jacket pocket for invoices.",
    features: [
      "Permanent Hot-Melt Adhesive",
      "Built-In Clear POD Pocket",
      "Waterproof & Tear Resistant",
      "Opaque Co-Extruded Poly Film"
    ],
    prices: {
      "50": 290.0,
      "100": 520.0,
      "300": 1450.0,
      "500": 2200.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/courier-bags.png",
    specifications: {
      "Box Type": "Courier Bag",
      "Material": "LDPE Poly Co-Ex",
      "Finish": "White Exterior / Black Interior",
      "Usage": "E-Commerce Parcel Dispatch",
      "Customization": "Available",
      "Country of Origin": "India"
    },
    rating: 4.9,
    reviewsCount: 198,
    isPopular: true
  },
  {
    id: "pb-bag-8-12",
    slug: "kraft-paper-shopping-bag-8x12",
    name: "Kraft Paper Shopping Bag with Handles - 8x12 Inch",
    category: "Paper Bags",
    categorySlug: "paper-bags",
    categoryId: "paper-bags",
    size_inches: "8 inch X 12 inch X 4 inch",
    size_inches_short: "8x12",
    size_cm: "20.32 cm x 30.48 cm x 10.16 cm",
    length_in: 8.0,
    width_in: 12.0,
    height_in: 4.0,
    length_cm: 20.32,
    width_cm: 30.48,
    height_cm: 10.16,
    description: "Eco-friendly brown kraft paper bag featuring twisted paper handles and reinforced bottom gusset for retail shopping.",
    features: [
      "120 GSM Virgin Kraft",
      "Twisted Paper Handles",
      "Reinforced Square Gusset",
      "100% Eco-Friendly & Compostable"
    ],
    prices: {
      "50": 420.0,
      "100": 780.0,
      "300": 2100.0,
      "500": 3200.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/paper-bags.png",
    specifications: {
      "Box Type": "Paper Bag",
      "Material": "Kraft Paper",
      "Finish": "Natural Brown",
      "Usage": "Boutiques & Retail Shopping",
      "Customization": "Brand Stamp Available",
      "Country of Origin": "India"
    },
    rating: 4.8,
    reviewsCount: 67
  },
  {
    id: "tr-2in-50m",
    slug: "kraft-paper-packaging-tape-2in",
    name: "Self-Adhesive Kraft Tape 2-Inch (50m Roll)",
    category: "Tape Rolls",
    categorySlug: "tape-rolls",
    categoryId: "tape-rolls",
    size_inches: "2 inch Width X 50m Roll",
    size_inches_short: "2in x 50m",
    size_cm: "5.08 cm x 50 m",
    length_in: 2.0,
    width_in: 2.0,
    height_in: 2.0,
    length_cm: 5.08,
    width_cm: 5.08,
    height_cm: 5.08,
    description: "Eco-friendly self-adhesive Kraft paper packing tape for tamper-evident sealing of corrugated shipping boxes.",
    features: [
      "Reinforced Fibers",
      "Strong Water-Activated Adhesive",
      "100% Recyclable",
      "Tamper Evident Seal"
    ],
    prices: {
      "50": 310.0,
      "100": 580.0,
      "300": 1600.0,
      "500": 2400.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/tape-rolls.png",
    specifications: {
      "Box Type": "Tape Roll",
      "Material": "Kraft Paper Tape",
      "Finish": "Natural Brown",
      "Usage": "Box Sealing & Shipping",
      "Customization": "Branded Print Available",
      "Country of Origin": "India"
    },
    rating: 4.9,
    reviewsCount: 156,
    isPopular: true
  },
  {
    id: "bw-1m-50m",
    slug: "protective-air-bubble-wrap-roll",
    name: "50m Air Bubble Wrap Roll (1m Width)",
    category: "Bubble Wrap",
    categorySlug: "bubble-wrap",
    categoryId: "bubble-wrap",
    size_inches: "39 inch Width X 50m Roll",
    size_inches_short: "39in x 50m",
    size_cm: "100 cm x 50 m",
    length_in: 39.0,
    width_in: 39.0,
    height_in: 18.0,
    length_cm: 100.0,
    width_cm: 100.0,
    height_cm: 45.0,
    description: "High-cushion air bubble packaging roll for protecting fragile items, glassware, and electronics during shipping.",
    features: [
      "High Shock Absorbance",
      "Dust Free LDPE Material",
      "100% Recyclable",
      "Moisture Protective"
    ],
    prices: {
      "50": 380.0,
      "100": 720.0,
      "300": 1950.0,
      "500": 3100.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/bubble-wrap.png",
    specifications: {
      "Box Type": "Bubble Wrap",
      "Material": "LDPE Bubble Wrap",
      "Finish": "Transparent Cushion",
      "Usage": "Fragile Item Wrapping",
      "Customization": "Available",
      "Country of Origin": "India"
    },
    rating: 4.9,
    reviewsCount: 124
  },
  {
    id: "cr-100cm-10m",
    slug: "single-face-corrugated-roll-100cm",
    name: "Single Face Corrugated Paper Roll (100cm x 10m)",
    category: "Corrugated Rolls",
    categorySlug: "corrugated-rolls",
    categoryId: "corrugated-rolls",
    size_inches: "39.3 inch Width X 10m Roll",
    size_inches_short: "100cm x 10m",
    size_cm: "100 cm x 10 m",
    length_in: 39.3,
    width_in: 39.3,
    height_in: 12.0,
    length_cm: 100.0,
    width_cm: 100.0,
    height_cm: 30.0,
    description: "Flexible single-face fluted corrugated paper roll for cushioning furniture, metal profiles, and heavy machinery parts.",
    features: [
      "C-Flute Flexible Board",
      "Protects Against Scratches & Dents",
      "100% Biodegradable Kraft",
      "Easy Scissors Cut"
    ],
    prices: {
      "50": 650.0,
      "100": 1200.0,
      "300": 3300.0,
      "500": 5100.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-rolls.png",
    specifications: {
      "Box Type": "Corrugated Roll",
      "Material": "Single Face Kraft Paper",
      "Finish": "Natural Fluted",
      "Usage": "Surface Protection & Wrapping",
      "Customization": "Available",
      "Country of Origin": "India"
    },
    rating: 4.8,
    reviewsCount: 45
  },
  {
    id: "cs-a4-sheet",
    slug: "a4-corrugated-cardboard-sheets",
    name: "A4 Corrugated Cardboard Sheets (Pack of 50)",
    category: "Corrugated Sheets",
    categorySlug: "corrugated-sheets",
    categoryId: "corrugated-sheets",
    size_inches: "11.7 inch X 8.3 inch X 0.15 inch",
    size_inches_short: "11.7x8.3",
    size_cm: "29.7 cm x 21.0 cm x 0.4 cm",
    length_in: 11.7,
    width_in: 8.3,
    height_in: 0.15,
    length_cm: 29.7,
    width_cm: 21.0,
    height_cm: 0.4,
    description: "Heavy-duty 3-ply corrugated cardboard separation sheets. Ideal for layer partitions inside shipping cartons, craft backing, and structural product protection.",
    features: [
      "3-Ply Single Wall Flute",
      "Precision Cut Margins",
      "Eco-Friendly Virgin Kraft",
      "High Compression Stiffness"
    ],
    prices: {
      "50": 350.0,
      "100": 640.0,
      "300": 1750.0,
      "500": 2700.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-sheets.png",
    specifications: {
      "Box Type": "Corrugated Sheet",
      "Material": "Kraft Cardboard",
      "Finish": "Natural Brown",
      "Usage": "Partition & Padding",
      "Customization": "Available",
      "Country of Origin": "India"
    },
    rating: 4.7,
    reviewsCount: 38
  },
  {
    id: "cpb-custom-logo",
    slug: "custom-logo-printed-mailer-box",
    name: "Custom Logo Printed Branded Box",
    category: "Custom Printed Boxes",
    categorySlug: "custom-printed-boxes",
    categoryId: "custom-printed-boxes",
    size_inches: "8 inch X 6 inch X 3 inch",
    size_inches_short: "8x6x3",
    size_cm: "20.32 cm x 15.24 cm x 7.62 cm",
    length_in: 8.0,
    width_in: 6.0,
    height_in: 3.0,
    length_cm: 20.32,
    width_cm: 15.24,
    height_cm: 7.62,
    description: "Custom printed branded packaging box printed with your company logo, custom pantone colors, and artwork.",
    features: [
      "High Definition Offset Printing",
      "Spot UV & Foil Stamping Options",
      "Free Dieline Template Assistance",
      "Full Interior & Exterior Print"
    ],
    prices: {
      "50": 790.0,
      "100": 1450.0,
      "300": 4100.0,
      "500": 6400.0
    },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/custom-printed-boxes.png",
    specifications: {
      "Box Type": "Custom Printed Box",
      "Material": "E-Flute Corrugated",
      "Finish": "Custom Artwork Print",
      "Usage": "Branded Unboxing & D2C",
      "Customization": "Full Custom Print",
      "Country of Origin": "India"
    },
    rating: 5.0,
    reviewsCount: 280,
    isPopular: true
  },
  {
    id: "tp-1",
    slug: "2-inch-brown-tape-65m",
    name: "2 Inch Brown Tape (65m Roll)",
    category: "Tape Rolls",
    categorySlug: "tape-rolls",
    categoryId: "tapes-packing-accessories",
    size_inches: "65m Roll X 2 Inch",
    size_inches_short: "2in x 65m",
    size_cm: "5.08 cm x 6500 cm",
    length_in: 65.0,
    width_in: 2.0,
    height_in: 2.0,
    length_cm: 6500,
    width_cm: 5.08,
    height_cm: 5.08,
    description: "Heavy-duty brown BOPP adhesive sealing tape for corrugated shipping boxes.",
    features: ["High Tack Acrylic Adhesive", "Tear Resistant BOPP", "Ideal for Cartons"],
    prices: { "50": 1600, "100": 3000, "300": 8400, "500": 13500 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/tape-rolls.png",
    specifications: { "Item": "BOPP Adhesive Tape", "Color": "Brown", "Width": "2 Inch (48mm)", "Length": "65 Meters" },
    rating: 4.8,
    reviewsCount: 210,
    isPopular: true
  },
  {
    id: "tp-2",
    slug: "2-inch-transparent-tape-65m",
    name: "2 Inch Transparent Tape (65m Roll)",
    category: "Tape Rolls",
    categorySlug: "tape-rolls",
    categoryId: "tapes-packing-accessories",
    size_inches: "65m Roll X 2 Inch",
    size_inches_short: "2in x 65m",
    size_cm: "5.08 cm x 6500 cm",
    length_in: 65.0,
    width_in: 2.0,
    height_in: 2.0,
    length_cm: 6500,
    width_cm: 5.08,
    height_cm: 5.08,
    description: "Clear BOPP packaging tape with strong adhesion for neat box sealing.",
    features: ["Crystal Clear Finish", "High Tensile Strength", "Weatherproof Coating"],
    prices: { "50": 1600, "100": 3000, "300": 8400, "500": 13500 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/tape-rolls.png",
    specifications: { "Item": "BOPP Adhesive Tape", "Color": "Transparent", "Width": "2 Inch (48mm)", "Length": "65 Meters" },
    rating: 4.9,
    reviewsCount: 174,
    isPopular: true
  },
  {
    id: "tp-3",
    slug: "3-inch-brown-heavy-tape-65m",
    name: "3 Inch Brown Heavy Tape (65m Roll)",
    category: "Tape Rolls",
    categorySlug: "tape-rolls",
    categoryId: "tapes-packing-accessories",
    size_inches: "65m Roll X 3 Inch",
    size_inches_short: "3in x 65m",
    size_cm: "7.62 cm x 6500 cm",
    length_in: 65.0,
    width_in: 3.0,
    height_in: 3.0,
    length_cm: 6500,
    width_cm: 7.62,
    height_cm: 7.62,
    description: "Extra wide 3-inch brown tape for extra heavy cartons and export packaging.",
    features: ["Extra Wide Coverage", "High Load Sealing", "Premium Film"],
    prices: { "50": 2400, "100": 4500, "300": 12600, "500": 20000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/tape-rolls.png",
    specifications: { "Item": "BOPP Heavy Duty Tape", "Color": "Brown", "Width": "3 Inch (72mm)", "Length": "65 Meters" },
    rating: 4.7,
    reviewsCount: 88
  },
  {
    id: "tp-4",
    slug: "fragile-printed-tape-2-inch-65m",
    name: "Fragile Printed Tape 2 Inch (65m Roll)",
    category: "Tape Rolls",
    categorySlug: "tape-rolls",
    categoryId: "tapes-packing-accessories",
    size_inches: "65m Roll X 2 Inch",
    size_inches_short: "2in x 65m",
    size_cm: "5.08 cm x 6500 cm",
    length_in: 65.0,
    width_in: 2.0,
    height_in: 2.0,
    length_cm: 6500,
    width_cm: 5.08,
    height_cm: 5.08,
    description: "Pre-printed FRAGILE tape with bold red warning text to protect delicate shipments.",
    features: ["High Visibility Warning", "Tamper Evident", "Strong Adhesion"],
    prices: { "50": 2100, "100": 3900, "300": 11100, "500": 17500 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/tape-rolls.png",
    specifications: { "Item": "Printed Caution Tape", "Print": "FRAGILE / HANDLE WITH CARE", "Width": "2 Inch", "Length": "65 Meters" },
    rating: 5.0,
    reviewsCount: 104
  },
  {
    id: "bw-1",
    slug: "10m-bubble-wrap-roll-1m-width",
    name: "10m Bubble Wrap Roll (1m Width)",
    category: "Bubble Wrap",
    categorySlug: "bubble-wrap",
    categoryId: "tapes-packing-accessories",
    size_inches: "10m Roll X 1m Width",
    size_inches_short: "1m x 10m",
    size_cm: "100 cm x 1000 cm",
    length_in: 393.7,
    width_in: 39.3,
    height_in: 4.0,
    length_cm: 1000,
    width_cm: 100,
    height_cm: 10,
    description: "High-cushioning air bubble film roll designed for wrapping fragile items and electronics.",
    features: ["Shock Absorption", "100% Recyclable LDPE", "Lightweight Protection"],
    prices: { "50": 4750, "100": 9000, "300": 25500, "500": 40000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/bubble-wrap.png",
    specifications: { "Item": "Bubble Wrap Roll", "GSM": "50 GSM", "Width": "1 Meter (3.28 ft)", "Length": "10 Meters" },
    rating: 4.8,
    reviewsCount: 54
  },
  {
    id: "bw-2",
    slug: "20m-bubble-wrap-roll-1m-width",
    name: "20m Bubble Wrap Roll (1m Width)",
    category: "Bubble Wrap",
    categorySlug: "bubble-wrap",
    categoryId: "tapes-packing-accessories",
    size_inches: "20m Roll X 1m Width",
    size_inches_short: "1m x 20m",
    size_cm: "100 cm x 2000 cm",
    length_in: 787.4,
    width_in: 39.3,
    height_in: 8.0,
    length_cm: 2000,
    width_cm: 100,
    height_cm: 20,
    description: "Medium length protective bubble cushioning roll for medium to high volume packing.",
    features: ["Durable Air Bubbles", "Puncture Resistant", "Moisture Proof"],
    prices: { "50": 8750, "100": 16500, "300": 46500, "500": 75000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/bubble-wrap.png",
    specifications: { "Item": "Bubble Wrap Roll", "GSM": "50 GSM", "Width": "1 Meter", "Length": "20 Meters" },
    rating: 4.9,
    reviewsCount: 92
  },
  {
    id: "bw-3",
    slug: "50m-bulk-bubble-wrap-roll-1m-width",
    name: "50m Bulk Bubble Wrap Roll (1m Width)",
    category: "Bubble Wrap",
    categorySlug: "bubble-wrap",
    categoryId: "tapes-packing-accessories",
    size_inches: "50m Roll X 1m Width",
    size_inches_short: "1m x 50m",
    size_cm: "100 cm x 5000 cm",
    length_in: 1968.5,
    width_in: 39.3,
    height_in: 18.0,
    length_cm: 5000,
    width_cm: 100,
    height_cm: 45,
    description: "Wholesale bulk 50-meter bubble wrap roll for warehouses, factories, and heavy e-commerce dispatch.",
    features: ["Maximum Economy Bulk Roll", "High Density Bubbles", "Superior Cushioning"],
    prices: { "50": 19000, "100": 36000, "300": 102000, "500": 165000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/bubble-wrap.png",
    specifications: { "Item": "Bulk Bubble Wrap Roll", "GSM": "50 GSM", "Width": "1 Meter", "Length": "50 Meters" },
    rating: 5.0,
    reviewsCount: 137
  },
  {
    id: "cr-1",
    slug: "10m-corrugated-paper-roll-3ft",
    name: "10m Corrugated Paper Roll (3ft Width)",
    category: "Corrugated Rolls",
    categorySlug: "corrugated-rolls",
    categoryId: "tapes-packing-accessories",
    size_inches: "10m Roll X 3ft Width",
    size_inches_short: "3ft x 10m",
    size_cm: "91.4 cm x 1000 cm",
    length_in: 393.7,
    width_in: 36.0,
    height_in: 12.0,
    length_cm: 1000,
    width_cm: 91.4,
    height_cm: 30,
    description: "Flexible single-face C-flute corrugated paper roll for wrapping industrial machinery and furniture.",
    features: ["C-Flute Cushioning", "Flexible Wrapping", "Biodegradable Kraft Paper"],
    prices: { "50": 6000, "100": 11200, "300": 31500, "500": 50000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-rolls.png",
    specifications: { "Item": "Corrugated Paper Roll", "Width": "3 Feet (90cm)", "Length": "10 Meters", "Fluting": "C-Flute" },
    rating: 4.7,
    reviewsCount: 34
  },
  {
    id: "cr-2",
    slug: "20m-corrugated-paper-roll-3ft",
    name: "20m Corrugated Paper Roll (3ft Width)",
    category: "Corrugated Rolls",
    categorySlug: "corrugated-rolls",
    categoryId: "tapes-packing-accessories",
    size_inches: "20m Roll X 3ft Width",
    size_inches_short: "3ft x 20m",
    size_cm: "91.4 cm x 2000 cm",
    length_in: 787.4,
    width_in: 36.0,
    height_in: 24.0,
    length_cm: 2000,
    width_cm: 91.4,
    height_cm: 60,
    description: "Durable corrugated wrapping paper roll providing scratch and dent protection during transport.",
    features: ["Impact Absorbing Fluting", "Easy Cut to Length", "Eco-Friendly"],
    prices: { "50": 11000, "100": 20500, "300": 58500, "500": 95000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-rolls.png",
    specifications: { "Item": "Corrugated Paper Roll", "Width": "3 Feet (90cm)", "Length": "20 Meters", "Fluting": "C-Flute" },
    rating: 4.8,
    reviewsCount: 59
  },
  {
    id: "cs-1",
    slug: "a4-size-cardboard-sheets-pack-50",
    name: "A4 Size Cardboard Sheets (Pack of 50)",
    category: "Corrugated Sheets",
    categorySlug: "corrugated-sheets",
    categoryId: "tapes-packing-accessories",
    size_inches: "11.7 inch X 8.3 inch",
    size_inches_short: "11.7x8.3",
    size_cm: "29.7 cm x 21.0 cm",
    length_in: 11.7,
    width_in: 8.3,
    height_in: 0.15,
    length_cm: 29.7,
    width_cm: 21.0,
    height_cm: 0.38,
    description: "Flat 3-ply corrugated cardboard partition sheets in standard A4 dimensions.",
    features: ["Flat Buffer Layer", "Rigid 3-Ply Board", "Craft & Envelope Stiffener"],
    prices: { "50": 5500, "100": 10000, "300": 28500, "500": 45000 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-sheets.png",
    specifications: { "Item": "Corrugated Cardboard Sheet", "Size": "A4 (297mm x 210mm)", "Pack": "50 Sheets", "Ply": "3-Ply" },
    rating: 4.9,
    reviewsCount: 76
  },
  {
    id: "cs-2",
    slug: "12x12-inch-square-cardboard-sheets-pack-50",
    name: "12 X 12 Inch Square Sheets (Pack of 50)",
    category: "Corrugated Sheets",
    categorySlug: "corrugated-sheets",
    categoryId: "tapes-packing-accessories",
    size_inches: "12 inch X 12 inch",
    size_inches_short: "12x12",
    size_cm: "30.48 cm x 30.48 cm",
    length_in: 12.0,
    width_in: 12.0,
    height_in: 0.15,
    length_cm: 30.48,
    width_cm: 30.48,
    height_cm: 0.38,
    description: "Square corrugated sheets for layering products inside shipping boxes and crates.",
    features: ["Square Partition Shape", "High Stacking Strength", "Recyclable Kraft"],
    prices: { "50": 9000, "100": 17000, "300": 48000, "500": 77500 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/corrugated-sheets.png",
    specifications: { "Item": "Corrugated Cardboard Sheet", "Size": "12 x 12 Inch", "Pack": "50 Sheets", "Ply": "3-Ply" },
    rating: 4.8,
    reviewsCount: 52
  },
  {
    id: "cb-bag-1",
    slug: "poly-courier-mailer-bags-pack-100",
    name: "Poly Courier Mailer Bags (Pack of 100)",
    category: "Courier Bags",
    categorySlug: "courier-bags",
    categoryId: "tapes-packing-accessories",
    size_inches: "10 inch X 12 inch",
    size_inches_short: "10x12",
    size_cm: "25.4 cm x 30.48 cm",
    length_in: 10.0,
    width_in: 12.0,
    height_in: 0.1,
    length_cm: 25.4,
    width_cm: 30.48,
    height_cm: 0.25,
    description: "Tamper-proof, waterproof co-extruded plastic courier bags with peel & seal adhesive strip.",
    features: ["Tamper Evident Seal", "Waterproof Poly Film", "Tear Proof Material"],
    prices: { "50": 800, "100": 1500, "300": 4200, "500": 6800 },
    contact_number: "+91 89039 27262",
    availability: "In Stock",
    image: "/images/courier-bags.png",
    specifications: { "Item": "Courier Mailer Bag", "Size": "10 x 12 Inch", "Material": "60 Micron Poly Film", "Pack": "100 Bags" },
    rating: 5.0,
    reviewsCount: 184,
    isPopular: true
  }
];

export const CATEGORIES = [
  {
    id: "mailer-boxes",
    name: "Mailer Boxes",
    slug: "mailer-boxes",
    description: "Sturdy and secure boxes perfect for e-commerce deliveries.",
    icon: "box",
    image: "/images/mailer-boxes.png",
    itemCount: 5
  },
  {
    id: "corrugated-boxes",
    name: "Corrugated Boxes",
    slug: "corrugated-boxes",
    description: "Strong and durable corrugated boxes for safe packaging and shipping.",
    icon: "layers",
    image: "/images/corrugated-boxes.png",
    itemCount: 4
  },
  {
    id: "shipping-boxes",
    name: "Shipping Boxes",
    slug: "shipping-boxes",
    description: "Reliable shipping boxes designed to protect your products.",
    icon: "truck",
    image: "/images/shipping-boxes.png",
    itemCount: 3
  },
  {
    id: "pizza-boxes",
    name: "Pizza Boxes",
    slug: "pizza-boxes",
    description: "Heat-resistant pizza boxes that keep your pizza fresh and hot.",
    icon: "pie-chart",
    image: "/images/pizza-boxes.png",
    itemCount: 2
  },
  {
    id: "mono-cartons",
    name: "Mono Cartons",
    slug: "mono-cartons",
    description: "Premium mono cartons for cosmetics, food, and retail packaging.",
    icon: "package",
    image: "/images/mono-cartons.png",
    itemCount: 2
  },
  {
    id: "courier-bags",
    name: "Courier Bags",
    slug: "courier-bags",
    description: "Lightweight and tamper-proof courier bags for secure deliveries.",
    icon: "shield-check",
    image: "/images/courier-bags.png",
    itemCount: 3
  },
  {
    id: "paper-bags",
    name: "Paper Bags",
    slug: "paper-bags",
    description: "Eco-friendly paper bags for shopping, retail, and promotional use.",
    icon: "shopping-bag",
    image: "/images/paper-bags.png",
    itemCount: 2
  },
  {
    id: "tape-rolls",
    name: "Tape Rolls",
    slug: "tape-rolls",
    description: "High-quality adhesive tape rolls for secure sealing and packaging.",
    icon: "tag",
    image: "/images/tape-rolls.png",
    itemCount: 4
  },
  {
    id: "bubble-wrap",
    name: "Bubble Wrap",
    slug: "bubble-wrap",
    description: "Protective bubble wrap for cushioning and safeguarding your items.",
    icon: "shield",
    image: "/images/bubble-wrap.png",
    itemCount: 2
  },
  {
    id: "corrugated-rolls",
    name: "Corrugated Rolls",
    slug: "corrugated-rolls",
    description: "Durable corrugated rolls for wrapping, cushioning, and packaging.",
    icon: "disc",
    image: "/images/corrugated-rolls.png",
    itemCount: 2
  },
  {
    id: "corrugated-sheets",
    name: "Corrugated Sheets",
    slug: "corrugated-sheets",
    description: "High-strength corrugated sheets for packaging and industrial use.",
    icon: "file-text",
    image: "/images/corrugated-sheets.png",
    itemCount: 2
  },
  {
    id: "tapes-packing-accessories",
    name: "Tapes & Packaging Accessories",
    slug: "tapes-packing-accessories",
    description: "Tapes, protective wraps, mailing bags and raw sheets to secure your retail shipments.",
    icon: "tag",
    image: "/images/tape-rolls.png",
    itemCount: 12
  },
  {
    id: "custom-printed-boxes",
    name: "Custom Printed Boxes",
    slug: "custom-printed-boxes",
    description: "Custom printed boxes to elevate your brand and leave a lasting impression.",
    icon: "sparkles",
    image: "/images/custom-printed-boxes.png",
    itemCount: 5
  }
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug || p.id === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return PRODUCTS.filter(
    (p) => p.categorySlug === categorySlug || p.categoryId === categorySlug
  );
}

export function getUnitPrice(product: Product, quantity: number): number {
  if (quantity >= 500 && product.prices["500"]) {
    return product.prices["500"] / 500;
  }
  if (quantity >= 300 && product.prices["300"]) {
    return product.prices["300"] / 300;
  }
  if (quantity >= 100 && product.prices["100"]) {
    return product.prices["100"] / 100;
  }
  if (product.prices["50"]) {
    return product.prices["50"] / 50;
  }
  return 10;
}

export function calculateTotalPrice(product: Product, quantity: number): number {
  const unitPrice = getUnitPrice(product, quantity);
  return unitPrice * quantity;
}
